### ISSUE TITLE
GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors. /data/data/com.termux/files/usr/bin/gh05t: line 1170: instagram-py: command not found

### ISSUE THREAD

**Issue by sober420** [GH05T-HUNTER5/GH05T-INSTA#248]
GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors.
/data/data/com.termux/files/usr/bin/gh05t: line 1170: instagram-py: command not found

I​ have​ this​ issue. I​'ve​ already​ run​ tor​ on​ other session.​ What​ can​ i​ do?

**Comment by sober420** [comment]
![Screenshot_20230609_170615_com duckduckgo mobile android](https://github.com/GH05T-HUNTER5/GH05T-INSTA/assets/88212371/6e7e7b8a-3789-4afe-a8e0-4e34729323f0)

**Comment by ABD123758** [comment]
Same doubt

**Comment by saad1rizvi** [comment]
I am having an issue while running this utility. After I start the attack it shows error every single time and does not start the attack. Even after uninstalling and then installing it again the error persists. If anyone has any idea about this please let me know....
![Error](https://github.com/GH05T-HUNTER5/GH05T-INSTA/assets/125978679/afa5100b-303b-4416-bc10-6a88e704f341)

**Comment by isazopadeiro** [comment]
> GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors. /data/data/com.termux/files/usr/bin/gh05t: line 1170: instagram-py: command not found

same issue here dude

**Comment by PrinceOjha0** [comment]
![image](https://github.com/GH05T-HUNTER5/GH05T-INSTA/assets/53299531/faa31879-942a-43a3-aa49-1b35f884c95c)
 issue review it or share me working version id

**Comment by GH05T-HUNTER5** [comment]
Try again 
Type this
`gh05t uninstall all`
`git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA`
`cd GH05T-INSTA`
`bash setup.sh`

**Comment by simohbarigo** [comment]
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by simohbarigo** [comment]
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by simohbarigo** [comment]
+] Started @ 2023-08-23 06:50:03.345555                                 
Traceback (most recent call last):                                       
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 87, in __init__                                          
    configuration = json.load(fp)                                        
                    ^^^^^^^^^^^^^                                        
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load         
    return loads(fp.read(),                                              
           ^^^^^^^^^^^^^^^^                                              
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads        
    return _default_decoder.decode(s)                                    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                    
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode        
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                    
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 8, in <module>
    sys.exit(ExecuteInstagramPy())
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy
    session = InstagramPySession(
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 90, in __init__
    "invalid configuration file at {}".format(configuraion))
                                              ^^^^^^^^^^^^
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by Kawazuri** [comment]
> Tente novamente Digite isto
> 
> `$ gh05t uninstall all`
> 
> `$ git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA`
> 
> `$ cd GH05T-INSTA`
> 
> `$ bash setup.sh`
> 
> `$ gh05t`

**Comment by Kawazuri** [comment]
Fiz a instalação dnv e mesmo assim não vai NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?
/data/data/com.termux/files/usr/bin/gh05t: line 264: security-gh05t: command not found
  +----------------------------------------------+
