### ISSUE TITLE
InstagramPySession.py Error

### ISSUE THREAD

**Issue by omgitsnate** [GH05T-HUNTER5/GH05T-INSTA#255]
Once the process starts I am getting the following error, this is a brand new BlackArch instance.

[+] Started @ 2023-08-16 19:30:38.377813
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 87, in __init__
    configuration = json.load(fp)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/instagram-py", line 8, in <module>
    sys.exit(ExecuteInstagramPy())
  File "/usr/lib/python3.10/site-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy
    session = InstagramPySession(
  File "/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 90, in __init__
    "invalid configuration file at {}".format(configuraion))
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by GH05T-HUNTER5** [comment]
pip install requests

**Comment by omgitsnate** [comment]
Thanks for the info, I did try that. Seems to be getting the same issue. I will keep digging on my end.

GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors.
Instagram-Py 2.0.7 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr.

[+] Started @ 2023-08-18 14:37:49.978331
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 87, in __init__
    configuration = json.load(fp)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/instagram-py", line 8, in <module>
    sys.exit(ExecuteInstagramPy())
  File "/usr/l
