### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Kalimata007** [GH05T-HUNTER5/GH05T-INSTA#257]
/Using cached instagram-py-2.0.7.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-mlq0e7jx/instagram-py_59c996e31bf941dbaf976ac87bd7643a/InstagramPy/__init__.py", line 11, in <module>
          from .InstagramPySession import InstagramPySession, DEFAULT_PATH
        File "/data/data/com.termux/files/usr/tmp/pip-install-mlq0e7jx/instagram-py_59c996e31bf941dbaf976ac87bd7643a/InstagramPy/InstagramPySession.py", line 11, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by GH05T-HUNTER5** [comment]
> /Using cached instagram-py-2.0.7.tar.gz (31 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [24 lines of output] Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in main() File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires self.run_setup() File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script) File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmc5s_yd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup exec(code, locals()) File "", line 13, in File "/data/data/com.termux/files/usr/tmp/pip-install-mlq0e7jx/instagram-py_59c996e31bf941dbaf976ac87bd7643a/InstagramPy/**init**.py", line 11, in from .InstagramPySession import InstagramPySession, DEFAULT_PATH File "/data/data/com.termux/files/usr/tmp/pip-install-mlq0e7jx/instagram-py_59c996e31bf941dbaf976ac87bd7643a/InstagramPy/InstagramPySession.py", line 11, in import requests ModuleNotFoundError: No module named 'requests' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
Try this 
pip install requests

**Comment by GH05T-HUNTER5** [comment]
Install

`pip install requests`

**Comment by Kalimata007** [comment]
ERROR: Could not find a version that satisfies the requirement request (from versions: none)
ERROR: No matching distribution found for request

Got this after pip install request
