### ISSUE TITLE
Can't finish install - getting error with instagram-py

### ISSUE THREAD

**Issue by SirGraecus** [GH05T-HUNTER5/GH05T-INSTA#258]
While install on termux, after command 'gh05t' I get the message ' Instagram-py command not located. To install Instagram-py, please execute the installation command: 'pip install Instagram-py' '

After command 'pip install Instagram-py' I get the message: 

Collecting instagram-py                              Using cached instagram-py-2.0.7.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error              
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1                                     ╰─> [24 lines of output]                               Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()                                           File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main              json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-d8h6m0z_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-d8h6m0z_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-d8h6m0z_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-d8h6m0z_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-4a_48w7p/instagram-py_c1464d8866fa4ab6bbee489483842efb/InstagramPy/__init__.py", line 11, in <module>
          from .InstagramPySession import InstagramPySession, DEFAULT_PATH
        File "/data/data/com.termux/files/usr/tmp/pip-install-4a_48w7p/instagram-py_c1464d8866fa4ab6bbee489483842efb/InstagramPy/InstagramPySession.py", line 11, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

After that not even ' gh05t uninstall all ' will work

**Comment by hopeapp-in** [comment]
This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by SHAIJANKHAN** [comment]
Please solve this problem

**Comment by SHAIJANKHAN** [comment]
![Uploading Screenshot_2024-02-10-22-39-55-68_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by reza780620** [comment]
منم همین مشکل را دارم چطور حلش کنم
