### ISSUE TITLE
Receiving this error again and agian even after installing  pip install requests

### ISSUE THREAD

**Issue by WardetWahaj** [GH05T-HUNTER5/GH05T-INSTA#259]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 87, in __init__
    configuration = json.load(fp)
                    ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 39 (char 327)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 8, in <module>
    sys.exit(ExecuteInstagramPy())
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy
    session = InstagramPySession(
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 90, in __init__
    "invalid configuration file at {}".format(configuraion))
                                              ^^^^^^^^^^^^
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by DangerWolf473** [comment]
Using this software on laptop

**Comment by Creepy2e** [comment]
i have the same error but i dont know why it comes everytime i have tor running too i have tryed to uninstall alll but nothing work
