### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by umarahmad200** [GH05T-HUNTER5/GH05T-INSTA#260]
Invalid configuration file at /root/instapy-config.json

**Comment by Creepy2e** [comment]
> Invalid configuration file at /root/instapy-config.json

you mean this is display by terminal?:

 Traceback (most recent call last):                                           
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 87, in __init__                                                  
    configuration = json.load(fp)                                            
                    ^^^^^^^^^^^^^                                            
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load             
    return loads(fp.read(),                                                  
           ^^^^^^^^^^^^^^^^                                                  
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads            
    return _default_decoder.decode(s)                                        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode            
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                        
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode        
    obj, end = self.scan_once(s, idx)                                        
               ^^^^^^^^^^^^^^^^^^^^^^                                        
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 39 (char 327)                                              
                                                                             
During handling of the above exception, another exception occurred:          

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 8, in <module>
    sys.exit(ExecuteInstagramPy())
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy
    session = InstagramPySession(
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 90, in __init__
    "invalid configuration file at {}".format(configuraion))
                                              ^^^^^^^^^^^^
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

i have this problem and i dont know how to fix it i have uninstall and install but everytime i get this error i hope anyone can help me

**Comment by Creepy2e** [comment]
> This script must be as root getting this after bash setup.sh cmd

Yes i have it run as Root But it doesnt work i have All Time the Same Error it doesnt work

**Comment by Aftershock3995** [comment]
I have this issue as well

**Comment by trashmanbrah** [comment]
me too
