### ISSUE TITLE
your tool DOES NOT work, fix it 

### ISSUE THREAD

**Issue by birdman-2** [GH05T-HUNTER5/GH05T-INSTA#268]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/InstagramPy/InstagramPySession.py", line 87, in init
configuration = json.load(fp)
File "/usr/lib/python3.10/json/init.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 39 (char 327)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/instagram-py", line 8, in
sys.exit(ExecuteInstagramPy())
File "/usr/local/lib/python3.10/dist-packages/InstagramPy/init.py", line 128, in ExecuteInstagramPy
session = InstagramPySession(
File "/usr/local/lib/python3.10/dist-packages/InstagramPy/InstagramPySession.py", line 90, in init
"invalid configuration file at {}".format(configuraion))
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by birdman-2** [comment]
i have tried the "pip install requests" and it didnt work
i have also tried to reinstall the tool and it still didnt work
i am wondering if this tool ever worked lol

**Comment by acalapatih** [comment]
UP
I've same trouble with this

**Comment by Z10n120** [comment]
sup do you know how i can get my password and username
?? i need some help dc is kingbob_6666

**Comment by Joynuldin** [comment]
Sure

**Comment by devmeireles** [comment]
I think saying "fix it' on an open source project will never be a good ideia, anyways, you can fix that with directly editing the `/usr/local/lib/python3.10/dist-packages/InstagramPy/InstagramPySession.py` file

So go to around line 90 then you can see:

```py

"invalid configuration file at {}".format(configuraion))
```

You can rename it to configuration, probably gonna work

**Comment by devmeireles** [comment]
have you tried to install instagram-py library?

In my case I was able to fix that with `pip3 install Instagram-py`

make sure to use the proper pip version

**Comment by Scotty2Hotty9898** [comment]
> I think saying "fix it' on an open source project will never be a good ideia, anyways, you can fix that with directly editing the `/usr/local/lib/python3.10/dist-packages/InstagramPy/InstagramPySession.py` file
> 
> So go to around line 90 then you can see:
> 
> ```python
> "invalid configuration file at {}".format(configuraion))
> ```
> 
> You can rename it to configuration, probably gonna work

I’m sorry, do you mean rename the whole line to just configuration? Like delete it completely and re type configuration? Could you give an example ?

**Comment by devmeireles** [comment]
> > I think saying "fix it' on an open source project will never be a good ideia, anyways, you can fix that with directly editing the `/usr/local/lib/python3.10/dist-packages/InstagramPy/InstagramPySession.py` file
> > So go to around line 90 then you can see:
> > ```python
> > "invalid configuration file at {}".format(configuraion))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can rename it to configuration, probably gonna work
> 
> I’m sorry, do you mean rename the whole line to just configuration? Like delete it completely and re type configuration? Could you give an example ?

No worries, you need to fix the typo on configuraion, this variable is declared as configuration and not configuraion, it must be enough to fix your issue

**Comment by Scotty2Hotty9898** [comment]
Oh okay, I got it thanks! Unfortunately my configuration is spelled correctly :( but I am still getting the same issue/error message. Do you have any other advice?
